version: '3.9'
services:
  web:
    container_name: web
    image: ferdinand:latest
    build: 
      context: .
      target: web
    depends_on:
      postgres:
        condition: service_healthy
  migrations:
    container_name: migrations
    image: ferdinand:latest
    build: 
      context: .
      target: migrations
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
