version: '3.9'
services:
  csharp-unit:
    container_name: csharp-unit-tests
    image: ferdinand:tests
    build:
      context: .
      target: tests
    environment:
      - TEST_TYPE=Unit
  csharp-integration:
    container_name: csharp-integration-tests
    image: ferdinand:tests
    build:
      context: .
      target: tests
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=${TESTCONTAINERS_HOST_OVERRIDE:-host.docker.internal}
      - TEST_TYPE=Integration
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
